apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario
spec:
  replicas: 2  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: supermario
      environment: QA
  template:
    metadata:
      labels:
        app: supermario
        environment: QA
    spec:
      containers:
      - name: mario-container
        image: sevenajay/mario:latest 
        ports:
        - containerPort: 80
